jaffle_shop:
  target: mysql
  outputs:
    postgres:
      type: postgres
      host: localhost
      user: "{{ env_var('POSTGRES_USERNAME') }}"
      password: "{{ env_var('POSTGRES_PW') }}"
      port: 5432
      dbname: dbt-tutorial # or database instead of dbname
      schema: jaffle_shop
    mysql:
      type: mysql
      server: localhost
      port: 3306
      schema: building-register
      username: "{{ env_var('MYSQL_USERNAME') }}"
      password: "{{ env_var('MYSQL_PW') }}"
      ssl_disabled: True
