jaffle_shop:
  target: postgres
  outputs:
    postgres:
      type: postgres
      host: localhost
      user: "{{ env_var('POSTGRES_USERNAME') }}"
      password: "{{ env_var('POSTGRES_PW') }}"
      port: 5432
      dbname: dbt-tutorial # or database instead of dbname
      schema: jaffle_shop
