jaffle_shop:
  target: 'dev'
  outputs:
    dev:
      type: postgres
      host: localhost
      user: "{{ env_var('POSTGRES_USERNAME') }}"
      password: "{{ env_var('POSTGRES_PW') }}"
      port: 5432
      dbname: dbt-tutorial # or database instead of dbname
      schema: jaffle_shop
#      threads: [optional, 1 or more]
#      [keepalives_idle](#keepalives_idle): 0 # default 0, indicating the system default. See below
#      connect_timeout: 10 # default 10 seconds
#      [retries](#retries): 1  # default 1 retry on error/timeout when opening connections
#      [search_path](#search_path): [optional, override the default postgres search_path]
#      [role](#role): [optional, set the role dbt assumes when executing queries]
#      [sslmode](#sslmode): [optional, set the sslmode used to connect to the database]
